Repository Fan-Tion/Back-End, pull requests merged in 2024-08, with the labels that each got.

#91 (feat:create-post)
  src/main/java/com/fantion/backend/auction/service/impl/AuctionServiceImpl.java
  src/main/java/com/fantion/backend/common/config/SecurityConfiguration.java
  src/main/java/com/fantion/backend/community/controller/CommunityController.java
  src/main/java/com/fantion/backend/community/dto/ImageDto.java
  src/main/java/com/fantion/backend/community/dto/PostDto.java
  src/main/java/com/fantion/backend/community/entity/Post.java
  src/main/java/com/fantion/backend/community/repository/PostRepository.java
  src/main/java/com/fantion/backend/community/service/CommunityService.java
  src/main/java/com/fantion/backend/community/service/impl/CommunityServiceImpl.java
  src/main/java/com/fantion/backend/exception/ErrorCode.java
  src/main/java/com/fantion/backend/member/auth/MemberAuthUtil.java
  src/main/java/com/fantion/backend/member/dto/MemberDto.java
  src/main/java/com/fantion/backend/member/jwt/JwtTokenProvider.java
  src/main/java/com/fantion/backend/member/service/impl/MemberServiceImpl.java
  src/main/java/com/fantion/backend/payment/service/impl/PaymentServiceImpl.java
  src/main/java/com/fantion/backend/type/PostStatus.java
Labels: enhancement, refactoring

#93 (refactor:auction-update)
  src/main/java/com/fantion/backend/auction/controller/AuctionController.java
  src/main/java/com/fantion/backend/auction/dto/AuctionUpdateDto.java
  src/main/java/com/fantion/backend/auction/service/AuctionService.java
  src/main/java/com/fantion/backend/auction/service/impl/AuctionServiceImpl.java
Labels: refactoring

#94 (refactor:auction-update)
  src/main/java/com/fantion/backend/auction/controller/AuctionController.java
  src/main/java/com/fantion/backend/auction/dto/AuctionUpdateDto.java
  src/main/java/com/fantion/backend/auction/service/AuctionService.java
  src/main/java/com/fantion/backend/auction/service/impl/AuctionServiceImpl.java
Labels: refactoring

#95 (refactor:auction-update)
  src/main/java/com/fantion/backend/auction/controller/AuctionController.java
  src/main/java/com/fantion/backend/auction/service/AuctionService.java
  src/main/java/com/fantion/backend/auction/service/impl/AuctionServiceImpl.java
Labels: refactoring

#99 (feat:get-post)
  src/main/java/com/fantion/backend/auction/controller/AuctionController.java
  src/main/java/com/fantion/backend/auction/service/AuctionService.java
  src/main/java/com/fantion/backend/auction/service/impl/AuctionServiceImpl.java
  src/main/java/com/fantion/backend/common/config/SecurityConfiguration.java
  src/main/java/com/fantion/backend/community/controller/CommunityController.java
  src/main/java/com/fantion/backend/community/dto/ImageDto.java
  src/main/java/com/fantion/backend/community/dto/PostDto.java
  src/main/java/com/fantion/backend/community/entity/Community.java
  src/main/java/com/fantion/backend/community/entity/Post.java
  src/main/java/com/fantion/backend/community/repository/CommunityRepository.java
  src/main/java/com/fantion/backend/community/repository/PostRepository.java
  src/main/java/com/fantion/backend/community/service/CommunityService.java
  src/main/java/com/fantion/backend/community/service/impl/CommunityServiceImpl.java
  src/main/java/com/fantion/backend/exception/ErrorCode.java
  src/main/java/com/fantion/backend/member/auth/MemberAuthUtil.java
  src/main/java/com/fantion/backend/member/dto/MemberDto.java
  src/main/java/com/fantion/backend/member/jwt/JwtTokenProvider.java
  src/main/java/com/fantion/backend/member/service/impl/MemberServiceImpl.java
  src/main/java/com/fantion/backend/payment/service/impl/PaymentServiceImpl.java
  src/main/java/com/fantion/backend/type/CommunityStatus.java
  src/main/java/com/fantion/backend/type/PostStatus.java
Labels: enhancement

#100 (feat:update-post)
  src/main/java/com/fantion/backend/community/controller/CommunityController.java
  src/main/java/com/fantion/backend/community/dto/CheckDto.java
  src/main/java/com/fantion/backend/community/dto/PostDto.java
  src/main/java/com/fantion/backend/community/service/CommunityService.java
  src/main/java/com/fantion/backend/community/service/impl/CommunityServiceImpl.java
Labels: enhancement

#101 (feat:delete-post)
  src/main/java/com/fantion/backend/auction/repository/AuctionRepository.java
  src/main/java/com/fantion/backend/community/controller/CommunityController.java
  src/main/java/com/fantion/backend/community/dto/PostDto.java
  src/main/java/com/fantion/backend/community/repository/PostRepository.java
  src/main/java/com/fantion/backend/community/service/CommunityService.java
  src/main/java/com/fantion/backend/community/service/impl/CommunityServiceImpl.java
  src/main/java/com/fantion/backend/member/service/impl/MemberServiceImpl.java
Labels: enhancement

#102 (feat:get-post-list)
  src/main/java/com/fantion/backend/auction/controller/AuctionController.java
  src/main/java/com/fantion/backend/auction/repository/AuctionRepository.java
  src/main/java/com/fantion/backend/community/controller/CommunityController.java
  src/main/java/com/fantion/backend/community/repository/PostRepository.java
  src/main/java/com/fantion/backend/community/service/CommunityService.java
  src/main/java/com/fantion/backend/community/service/impl/CommunityServiceImpl.java
  src/main/java/com/fantion/backend/member/service/impl/MemberServiceImpl.java
Labels: enhancement

#103 (feat:search-post)
  src/main/java/com/fantion/backend/community/controller/CommunityController.java
  src/main/java/com/fantion/backend/community/repository/PostRepository.java
  src/main/java/com/fantion/backend/community/service/CommunityService.java
  src/main/java/com/fantion/backend/community/service/impl/CommunityServiceImpl.java
  src/main/java/com/fantion/backend/member/dto/SignupDto.java
  src/main/java/com/fantion/backend/type/PostSearchOption.java
Labels: enhancement

#105 채널 CRUD API 추가
  src/main/java/com/fantion/backend/auction/controller/BidController.java
  src/main/java/com/fantion/backend/auction/service/SseEmitterService.java
  src/main/java/com/fantion/backend/auction/service/impl/BidServiceImpl.java
  src/main/java/com/fantion/backend/auction/service/impl/RedisMessageServiceImpl.java
  src/main/java/com/fantion/backend/auction/service/impl/SseEmitterServiceImpl.java
  src/main/java/com/fantion/backend/common/component/RedisSubscriber.java
  src/main/java/com/fantion/backend/community/controller/CommunityController.java
  src/main/java/com/fantion/backend/community/dto/ChannelDto.java
  src/main/java/com/fantion/backend/community/dto/ChannelEditDto.java
  src/main/java/com/fantion/backend/community/dto/ChannelRemoveDto.java
  src/main/java/com/fantion/backend/community/entity/Channel.java
  src/main/java/com/fantion/backend/community/repository/ChannelRepository.java
  src/main/java/com/fantion/backend/community/service/CommunityService.java
  src/main/java/com/fantion/backend/community/service/impl/CommunityServiceImpl.java
  src/main/java/com/fantion/backend/type/ChannelStatus.java
Labels: enhancement

#109 (refactor:edit-channel)
  src/main/java/com/fantion/backend/common/component/S3Uploader.java
  src/main/java/com/fantion/backend/community/controller/CommunityController.java
  src/main/java/com/fantion/backend/community/dto/ChannelDto.java
  src/main/java/com/fantion/backend/community/dto/ChannelEditDto.java
  src/main/java/com/fantion/backend/community/dto/ChannelRemoveDto.java
  src/main/java/com/fantion/backend/community/dto/CheckDto.java
  src/main/java/com/fantion/backend/community/dto/PostDto.java
  src/main/java/com/fantion/backend/community/entity/Channel.java
  src/main/java/com/fantion/backend/community/entity/Post.java
  src/main/java/com/fantion/backend/community/repository/ChannelRepository.java
  src/main/java/com/fantion/backend/community/repository/PostRepository.java
  src/main/java/com/fantion/backend/community/service/CommunityService.java
  src/main/java/com/fantion/backend/community/service/impl/CommunityServiceImpl.java
  src/main/java/com/fantion/backend/member/service/impl/MemberServiceImpl.java
Labels: refactoring

#110 채널 전체 조회 API 추가
  src/main/java/com/fantion/backend/auction/controller/BidController.java
  src/main/java/com/fantion/backend/auction/service/SseEmitterService.java
  src/main/java/com/fantion/backend/auction/service/impl/BidServiceImpl.java
  src/main/java/com/fantion/backend/auction/service/impl/RedisMessageServiceImpl.java
  src/main/java/com/fantion/backend/auction/service/impl/SseEmitterServiceImpl.java
  src/main/java/com/fantion/backend/common/component/RedisSubscriber.java
  src/main/java/com/fantion/backend/community/controller/CommunityController.java
  src/main/java/com/fantion/backend/community/dto/ChannelAllDto.java
  src/main/java/com/fantion/backend/community/dto/ChannelDto.java
  src/main/java/com/fantion/backend/community/dto/ChannelEditDto.java
  src/main/java/com/fantion/backend/community/dto/ChannelRemoveDto.java
  src/main/java/com/fantion/backend/community/dto/CheckDto.java
  src/main/java/com/fantion/backend/community/dto/ImageDto.java
  src/main/java/com/fantion/backend/community/dto/PostDto.java
  src/main/java/com/fantion/backend/community/entity/Channel.java
  src/main/java/com/fantion/backend/community/entity/Community.java
  src/main/java/com/fantion/backend/community/entity/Post.java
  src/main/java/com/fantion/backend/community/repository/ChannelRepository.java
  src/main/java/com/fantion/backend/community/repository/CommunityRepository.java
  src/main/java/com/fantion/backend/community/repository/PostRepository.java
  src/main/java/com/fantion/backend/community/service/CommunityService.java
  src/main/java/com/fantion/backend/community/service/impl/CommunityServiceImpl.java
  src/main/java/com/fantion/backend/exception/ErrorCode.java
  src/main/java/com/fantion/backend/type/ChannelStatus.java
  src/main/java/com/fantion/backend/type/CommunityStatus.java
  src/main/resources/application.yml
Labels: enhancement

#116 게시글 추천, 채널 정보 조회 api 추가
  src/main/java/com/fantion/backend/community/controller/CommunityController.java
  src/main/java/com/fantion/backend/community/dto/PostLikeDto.java
  src/main/java/com/fantion/backend/community/entity/PostLike.java
  src/main/java/com/fantion/backend/community/repository/PostLikeRepository.java
  src/main/java/com/fantion/backend/community/service/CommunityService.java
  src/main/java/com/fantion/backend/community/service/impl/CommunityServiceImpl.java
Labels: enhancement

#120 게시판 신고 api 추가 및 입찰시간 포맷 적용
  src/main/java/com/fantion/backend/auction/dto/BidDto.java
  src/main/java/com/fantion/backend/auction/service/impl/BidServiceImpl.java
  src/main/java/com/fantion/backend/community/controller/CommunityController.java
  src/main/java/com/fantion/backend/community/dto/PostReportDto.java
  src/main/java/com/fantion/backend/community/entity/PostReport.java
  src/main/java/com/fantion/backend/community/repository/PostReportRepository.java
  src/main/java/com/fantion/backend/community/service/CommunityService.java
  src/main/java/com/fantion/backend/community/service/impl/CommunityServiceImpl.java
  src/main/java/com/fantion/backend/exception/ErrorCode.java
  src/main/resources/application.yml
Labels: enhancement

#122 (fix:naver-link)
  src/main/java/com/fantion/backend/auction/repository/AuctionReportRepository.java
  src/main/java/com/fantion/backend/auction/service/impl/AuctionServiceImpl.java
  src/main/java/com/fantion/backend/auction/service/impl/BidServiceImpl.java
  src/main/java/com/fantion/backend/community/repository/CommentRepository.java
  src/main/java/com/fantion/backend/community/repository/PostRepository.java
  src/main/java/com/fantion/backend/community/service/impl/CommunityServiceImpl.java
  src/main/java/com/fantion/backend/exception/ErrorCode.java
  src/main/java/com/fantion/backend/member/controller/MemberController.java
  src/main/java/com/fantion/backend/member/service/MemberService.java
  src/main/java/com/fantion/backend/member/service/impl/MemberServiceImpl.java
Labels: refactoring
