Repository Fan-Tion/Back-End, pull requests merged in 2024-07, with the labels that each got.

#6 Feat : 입찰 생성 기능 추가
  src/main/java/com/fantion/backend/auction/controller/AuctionController.java
  src/main/java/com/fantion/backend/auction/dto/BidDto.java
  src/main/java/com/fantion/backend/auction/entity/Bid.java
  src/main/java/com/fantion/backend/auction/repository/BidRepository.java
  src/main/java/com/fantion/backend/auction/service/AuctionService.java
  src/main/java/com/fantion/backend/auction/service/impl/AuctionServiceImpl.java
Labels: enhancement

#7 (feat:request-payment)
  pull_request_template.md
  src/main/java/com/fantion/backend/configuration/SecurityConfiguration.java
  src/main/java/com/fantion/backend/exception/impl/NotFoundMemberException.java
  src/main/java/com/fantion/backend/member/entity/Member.java
  src/main/java/com/fantion/backend/member/repository/MemberRepository.java
  src/main/java/com/fantion/backend/payment/controller/PaymentController.java
  src/main/java/com/fantion/backend/payment/dto/PaymentDto.java
  src/main/java/com/fantion/backend/payment/entity/Payment.java
  src/main/java/com/fantion/backend/payment/repository/PaymentRepository.java
  src/main/java/com/fantion/backend/payment/service/PaymentService.java
  src/main/java/com/fantion/backend/payment/service/impl/PaymentServiceImpl.java
  src/main/java/com/fantion/backend/type/MemberStatus.java
  src/main/java/com/fantion/backend/type/PaymentType.java
Labels: enhancement

#10 (feat:success-payment)
  build.gradle
  src/main/java/com/fantion/backend/FantionApplication.java
  src/main/java/com/fantion/backend/configuration/RedisConfiguration.java
  src/main/java/com/fantion/backend/exception/AbstractException.java
  src/main/java/com/fantion/backend/exception/CustomExceptionHandler.java
  src/main/java/com/fantion/backend/exception/ErrorResponse.java
  src/main/java/com/fantion/backend/exception/impl/ParsingException.java
  src/main/java/com/fantion/backend/exception/impl/TossApiException.java
  src/main/java/com/fantion/backend/payment/component/PaymentClient.java
  src/main/java/com/fantion/backend/payment/component/PaymentComponent.java
  src/main/java/com/fantion/backend/payment/controller/PaymentController.java
  src/main/java/com/fantion/backend/payment/dto/ConfirmDto.java
  src/main/java/com/fantion/backend/payment/dto/PaymentDto.java
  src/main/java/com/fantion/backend/payment/dto/ResponseDto.java
  src/main/java/com/fantion/backend/payment/repository/PaymentRepository.java
  src/main/java/com/fantion/backend/payment/service/PaymentService.java
  src/main/java/com/fantion/backend/payment/service/impl/PaymentServiceImpl.java
  src/main/java/com/fantion/backend/type/PaymentType.java
Labels: enhancement

#11 (feat:fail-payment)
  src/main/java/com/fantion/backend/payment/controller/PaymentController.java
  src/main/java/com/fantion/backend/payment/dto/ResponseDto.java
  src/main/java/com/fantion/backend/payment/service/PaymentService.java
  src/main/java/com/fantion/backend/payment/service/impl/PaymentServiceImpl.java
Labels: enhancement

#14 feat: 경매 리스트, 검색 기능 추가
  images/auction/1/1.jpg
  images/auction/1/2.jpg
  images/auction/1/3.jpg
  src/main/java/com/fantion/backend/auction/controller/AuctionController.java
  src/main/java/com/fantion/backend/auction/dto/AuctionDto.java
  src/main/java/com/fantion/backend/auction/dto/SearchDto.java
  src/main/java/com/fantion/backend/auction/repository/AuctionRepository.java
  src/main/java/com/fantion/backend/auction/service/AuctionService.java
  src/main/java/com/fantion/backend/auction/service/impl/AuctionServiceImpl.java
  src/main/java/com/fantion/backend/exception/CustomExceptionHandler.java
  src/main/java/com/fantion/backend/exception/impl/AuctionHttpMessageNotReadableException.java
  src/main/java/com/fantion/backend/exception/impl/AuctionNotFoundException.java
  src/main/java/com/fantion/backend/exception/impl/ImageInternalServerException.java
  src/main/java/com/fantion/backend/exception/impl/ImageMalformedURLException.java
  src/main/java/com/fantion/backend/exception/impl/ImageNotFoundException.java
  src/main/java/com/fantion/backend/type/SearchType.java
  src/main/resources/application.yaml
Labels: enhancement

#15 (feat:signup), (refactor:success-payment)
  build.gradle
  src/main/java/com/fantion/backend/configuration/SecurityConfiguration.java
  src/main/java/com/fantion/backend/exception/impl/DuplicateEmailException.java
  src/main/java/com/fantion/backend/exception/impl/ImageSaveException.java
  src/main/java/com/fantion/backend/exception/impl/InvalidEmailException.java
  src/main/java/com/fantion/backend/exception/impl/UnsupportedImageTypeException.java
  src/main/java/com/fantion/backend/member/controller/MemberController.java
  src/main/java/com/fantion/backend/member/dto/SignupDto.java
  src/main/java/com/fantion/backend/member/entity/BalanceHistory.java
  src/main/java/com/fantion/backend/member/entity/Money.java
  src/main/java/com/fantion/backend/member/repository/BalanceHistoryRepository.java
  src/main/java/com/fantion/backend/member/repository/MoneyRepository.java
  src/main/java/com/fantion/backend/member/service/MemberService.java
  src/main/java/com/fantion/backend/member/service/impl/MemberServiceImpl.java
  src/main/java/com/fantion/backend/payment/controller/PaymentController.java
  src/main/java/com/fantion/backend/payment/dto/PaymentDto.java
  src/main/java/com/fantion/backend/payment/service/impl/PaymentServiceImpl.java
  src/main/java/com/fantion/backend/type/BalanceType.java
Labels: enhancement, refactorign

#12 Feat : 입찰가 갱신 및 경매 상세보기 추가
  src/main/java/com/fantion/backend/auction/controller/AuctionController.java
  src/main/java/com/fantion/backend/auction/controller/BidController.java
  src/main/java/com/fantion/backend/auction/dto/BidDto.java
  src/main/java/com/fantion/backend/auction/repository/SseEmitterRepository.java
  src/main/java/com/fantion/backend/auction/repository/impl/SseEmitterRepositoryImpl.java
  src/main/java/com/fantion/backend/auction/service/AuctionService.java
  src/main/java/com/fantion/backend/auction/service/BidService.java
  src/main/java/com/fantion/backend/auction/service/RedisMessageService.java
  src/main/java/com/fantion/backend/auction/service/SseEmitterService.java
  src/main/java/com/fantion/backend/auction/service/impl/AuctionServiceImpl.java
  src/main/java/com/fantion/backend/auction/service/impl/BidServiceImpl.java
  src/main/java/com/fantion/backend/auction/service/impl/RedisMessageServiceImpl.java
  src/main/java/com/fantion/backend/auction/service/impl/SseEmitterServiceImpl.java
  src/main/java/com/fantion/backend/configuration/RedisConfiguration.java
  src/main/java/com/fantion/backend/configuration/RedisPublisher.java
  src/main/java/com/fantion/backend/configuration/RedisSubscriber.java
  src/main/java/com/fantion/backend/configuration/WebSocketConfig.java
Labels: enhancement, refactorign

#19 (feat:signin)
  build.gradle
  src/main/java/com/fantion/backend/configuration/SecurityConfiguration.java
  src/main/java/com/fantion/backend/exception/impl/InvalidPasswordException.java
  src/main/java/com/fantion/backend/exception/impl/SuspendedMemberException.java
  src/main/java/com/fantion/backend/member/controller/MemberController.java
  src/main/java/com/fantion/backend/member/dto/SigninDto.java
  src/main/java/com/fantion/backend/member/dto/TokenDto.java
  src/main/java/com/fantion/backend/member/jwt/JwtTokenFilter.java
  src/main/java/com/fantion/backend/member/jwt/JwtTokenProvider.java
  src/main/java/com/fantion/backend/member/service/MemberService.java
  src/main/java/com/fantion/backend/member/service/impl/MemberServiceImpl.java
Labels: enhancement

#20 chore:카테고리 추가 및 검색카테고리 이름 변경
  src/main/java/com/fantion/backend/auction/dto/AuctionDto.java
  src/main/java/com/fantion/backend/auction/dto/SearchDto.java
  src/main/java/com/fantion/backend/auction/entity/Auction.java
  src/main/java/com/fantion/backend/auction/service/impl/AuctionServiceImpl.java
  src/main/java/com/fantion/backend/type/CategoryType.java
Labels: refactorign

#23 Refactor : 입찰시 예치금 확인 및 입찰마감 (낙찰 유찰) 처리
  build.gradle
  src/main/java/com/fantion/backend/auction/controller/BidController.java
  src/main/java/com/fantion/backend/auction/dto/BalanceCheckDto.java
  src/main/java/com/fantion/backend/auction/dto/BidDto.java
  src/main/java/com/fantion/backend/auction/dto/BuyNowDto.java
  src/main/java/com/fantion/backend/auction/entity/Auction.java
  src/main/java/com/fantion/backend/auction/entity/Bid.java
  src/main/java/com/fantion/backend/auction/entity/JoinAuction.java
  src/main/java/com/fantion/backend/auction/repository/AuctionRepository.java
  src/main/java/com/fantion/backend/auction/repository/BidRepository.java
  src/main/java/com/fantion/backend/auction/service/BidService.java
  src/main/java/com/fantion/backend/auction/service/impl/BidServiceImpl.java
  src/main/java/com/fantion/backend/auction/service/impl/SseEmitterServiceImpl.java
  src/main/java/com/fantion/backend/configuration/SecurityConfiguration.java
  src/main/java/com/fantion/backend/exception/BidAbstractException.java
  src/main/java/com/fantion/backend/exception/BidErrorResponse.java
  src/main/java/com/fantion/backend/exception/CustomExceptionHandler.java
  src/main/java/com/fantion/backend/exception/ErrorCode.java
  src/main/java/com/fantion/backend/exception/impl/BidException.java
  src/main/java/com/fantion/backend/member/auth/MemberAuthUtil.java
  src/main/java/com/fantion/backend/member/entity/Money.java
  src/test/java/com/fantion/backend/auction/service/impl/BidServiceImplTest.java
Labels: enhancement, refactorign

#21 (refactor:signup)
  src/main/java/com/fantion/backend/exception/impl/DuplicateNicknameException.java
  src/main/java/com/fantion/backend/exception/impl/InvalidNicknameException.java
  src/main/java/com/fantion/backend/member/controller/MemberController.java
  src/main/java/com/fantion/backend/member/dto/CheckDto.java
  src/main/java/com/fantion/backend/member/repository/MemberRepository.java
  src/main/java/com/fantion/backend/member/service/MemberService.java
  src/main/java/com/fantion/backend/member/service/impl/MemberServiceImpl.java
Labels: enhancement, refactorign

#25 (feat:naver-signin)
  build.gradle
  src/main/java/com/fantion/backend/exception/CustomExceptionHandler.java
  src/main/java/com/fantion/backend/exception/impl/DuplicateLinkException.java
  src/main/java/com/fantion/backend/exception/impl/LinkedEmailException.java
  src/main/java/com/fantion/backend/exception/impl/OtherSnsLinkException.java
  src/main/java/com/fantion/backend/exception/impl/SnsNotLinkedException.java
  src/main/java/com/fantion/backend/member/configuration/NaverConfiguration.java
  src/main/java/com/fantion/backend/member/configuration/NaverLoginClient.java
  src/main/java/com/fantion/backend/member/configuration/NaverProfileClient.java
  src/main/java/com/fantion/backend/member/controller/MemberController.java
  src/main/java/com/fantion/backend/member/dto/NaverMemberDto.java
  src/main/java/com/fantion/backend/member/dto/SignupDto.java
  src/main/java/com/fantion/backend/member/dto/TokenDto.java
  src/main/java/com/fantion/backend/member/entity/Member.java
  src/main/java/com/fantion/backend/member/entity/Money.java
  src/main/java/com/fantion/backend/member/jwt/JwtTokenProvider.java
  src/main/java/com/fantion/backend/member/repository/MemberRepository.java
  src/main/java/com/fantion/backend/member/service/MemberService.java
  src/main/java/com/fantion/backend/member/service/impl/MemberServiceImpl.java
  src/main/java/com/fantion/backend/payment/component/PaymentComponent.java
  src/main/java/com/fantion/backend/payment/service/PaymentService.java
  src/main/java/com/fantion/backend/payment/service/impl/PaymentServiceImpl.java
  src/test/java/com/fantion/backend/NaverServiceTest.java
Labels: enhancement

#28 Refactor : 예외 처리 수정
  src/main/java/com/fantion/backend/auction/controller/BidController.java
  src/main/java/com/fantion/backend/auction/dto/BidSubscribeDto.java
  src/main/java/com/fantion/backend/auction/service/BidService.java
  src/main/java/com/fantion/backend/auction/service/impl/AuctionServiceImpl.java
  src/main/java/com/fantion/backend/auction/service/impl/BidServiceImpl.java
  src/main/java/com/fantion/backend/configuration/SecurityConfiguration.java
  src/main/java/com/fantion/backend/exception/CustomExceptionHandler.java
  src/main/java/com/fantion/backend/exception/ErrorCode.java
  src/main/java/com/fantion/backend/exception/FantionAbstractException.java
  src/main/java/com/fantion/backend/exception/FantionErrorResponse.java
  src/main/java/com/fantion/backend/exception/impl/FantionException.java
  src/main/java/com/fantion/backend/member/entity/Money.java
Labels: refactorign

#30 Feat : 입찰취소 api 추가 및 비공개 입찰 관련 수정
  src/main/java/com/fantion/backend/FantionApplication.java
  src/main/java/com/fantion/backend/auction/controller/BidController.java
  src/main/java/com/fantion/backend/auction/dto/BidCancelDto.java
  src/main/java/com/fantion/backend/auction/dto/BidDto.java
  src/main/java/com/fantion/backend/auction/repository/AuctionRepository.java
  src/main/java/com/fantion/backend/auction/repository/BidRepository.java
  src/main/java/com/fantion/backend/auction/service/BidService.java
  src/main/java/com/fantion/backend/auction/service/impl/BidServiceImpl.java
  src/main/java/com/fantion/backend/exception/ErrorCode.java
  src/test/java/com/fantion/backend/auction/service/impl/BidServiceImplTest.java
Labels: enhancement, refactorign

#32 (feat:withdrawal)
  src/main/java/com/fantion/backend/auction/dto/BidDto.java
  src/main/java/com/fantion/backend/exception/ErrorCode.java
  src/main/java/com/fantion/backend/member/configuration/NaverLoginClient.java
  src/main/java/com/fantion/backend/member/controller/MemberController.java
  src/main/java/com/fantion/backend/member/dto/NaverLinkDto.java
  src/main/java/com/fantion/backend/member/jwt/JwtTokenFilter.java
  src/main/java/com/fantion/backend/member/service/MemberService.java
  src/main/java/com/fantion/backend/member/service/impl/MemberServiceImpl.java
Labels: enhancement

#34 (feat:s3)
  build.gradle
  src/main/java/com/fantion/backend/auction/controller/AuctionController.java
  src/main/java/com/fantion/backend/configuration/S3Configuration.java
  src/main/java/com/fantion/backend/configuration/S3Uploader.java
  src/main/java/com/fantion/backend/configuration/SecurityConfiguration.java
  src/main/java/com/fantion/backend/member/controller/MemberController.java
  src/main/java/com/fantion/backend/member/jwt/JwtTokenFilter.java
  src/main/java/com/fantion/backend/member/service/impl/MemberServiceImpl.java
Labels: enhancement

#36 Feat : 인수&인계 확인 API 추가
  src/main/java/com/fantion/backend/auction/controller/BidController.java
  src/main/java/com/fantion/backend/auction/dto/HandOverDto.java
  src/main/java/com/fantion/backend/auction/entity/Auction.java
  src/main/java/com/fantion/backend/auction/service/BidService.java
  src/main/java/com/fantion/backend/auction/service/impl/BidServiceImpl.java
  src/main/java/com/fantion/backend/exception/ErrorCode.java
  src/main/java/com/fantion/backend/member/entity/BalanceHistory.java
  src/main/java/com/fantion/backend/member/entity/Money.java
  src/main/resources/application.yml
  src/test/java/com/fantion/backend/auction/service/impl/BidServiceImplTest.java
Labels: enhancement

#40 (feat:naverUnlink)
  src/main/java/com/fantion/backend/auction/controller/AuctionController.java
  src/main/java/com/fantion/backend/exception/ErrorCode.java
  src/main/java/com/fantion/backend/member/controller/MemberController.java
  src/main/java/com/fantion/backend/member/service/MemberService.java
  src/main/java/com/fantion/backend/member/service/impl/MemberServiceImpl.java
  src/test/java/com/fantion/backend/MemberServiceTest.java
Labels: enhancement, refactorign

#41 Feat : 거래중인 경매 물품 조회 API 추가
  src/main/java/com/fantion/backend/auction/controller/AuctionController.java
  src/main/java/com/fantion/backend/auction/controller/BidController.java
  src/main/java/com/fantion/backend/auction/dto/AuctionFavoriteDto.java
  src/main/java/com/fantion/backend/auction/dto/BidSuccessListDto.java
  src/main/java/com/fantion/backend/auction/entity/FavoriteAuction.java
  src/main/java/com/fantion/backend/auction/repository/AuctionRepository.java
  src/main/java/com/fantion/backend/auction/repository/FavoriteAuctionRepository.java
  src/main/java/com/fantion/backend/auction/service/AuctionService.java
  src/main/java/com/fantion/backend/auction/service/BidService.java
  src/main/java/com/fantion/backend/auction/service/impl/AuctionServiceImpl.java
  src/main/java/com/fantion/backend/auction/service/impl/BidServiceImpl.java
Labels: enhancement

#49 feat/getmyinfo
  src/main/java/com/fantion/backend/member/controller/MemberController.java
  src/main/java/com/fantion/backend/member/dto/MemberDto.java
  src/main/java/com/fantion/backend/member/service/MemberService.java
  src/main/java/com/fantion/backend/member/service/impl/MemberServiceImpl.java
Labels: enhancement

#50 feat/myinfoedit
  src/main/java/com/fantion/backend/member/controller/MemberController.java
  src/main/java/com/fantion/backend/member/dto/MemberDto.java
  src/main/java/com/fantion/backend/member/service/MemberService.java
  src/main/java/com/fantion/backend/member/service/impl/MemberServiceImpl.java
  src/main/java/com/fantion/backend/payment/service/impl/PaymentServiceImpl.java
Labels: enhancement

#52 Feat : 구매 철회 API 추가
  src/main/java/com/fantion/backend/auction/controller/BidController.java
  src/main/java/com/fantion/backend/auction/dto/BidAuctionCancelDto.java
  src/main/java/com/fantion/backend/auction/entity/Auction.java
  src/main/java/com/fantion/backend/auction/service/BidService.java
  src/main/java/com/fantion/backend/auction/service/impl/BidServiceImpl.java
  src/main/java/com/fantion/backend/exception/ErrorCode.java
  src/main/java/com/fantion/backend/member/entity/Money.java
Labels: enhancement

#54 Dev
  build.gradle
  src/main/java/com/fantion/backend/auction/controller/BidController.java
  src/main/java/com/fantion/backend/auction/dto/BidAuctionCancelDto.java
  src/main/java/com/fantion/backend/auction/entity/Auction.java
  src/main/java/com/fantion/backend/auction/repository/AuctionRepository.java
  src/main/java/com/fantion/backend/auction/service/AuctionService.java
  src/main/java/com/fantion/backend/auction/service/BidService.java
  src/main/java/com/fantion/backend/auction/service/impl/AuctionServiceImpl.java
  src/main/java/com/fantion/backend/auction/service/impl/BidServiceImpl.java
  src/main/java/com/fantion/backend/auction/service/impl/RedisMessageServiceImpl.java
  src/main/java/com/fantion/backend/common/component/MailComponents.java
  src/main/java/com/fantion/backend/common/component/RedisPublisher.java
  src/main/java/com/fantion/backend/common/component/RedisSubscriber.java
  src/main/java/com/fantion/backend/common/component/S3Uploader.java
  src/main/java/com/fantion/backend/common/component/ScheduledTasks.java
  src/main/java/com/fantion/backend/common/config/RedisConfiguration.java
  src/main/java/com/fantion/backend/exception/ErrorCode.java
  src/main/java/com/fantion/backend/member/controller/MemberController.java
  src/main/java/com/fantion/backend/member/dto/MemberDto.java
  src/main/java/com/fantion/backend/member/dto/RatingRequestDto.java
  src/main/java/com/fantion/backend/member/dto/ResetPasswordDto.java
  src/main/java/com/fantion/backend/member/entity/Money.java
  src/main/java/com/fantion/backend/member/entity/RatingHistory.java
  src/main/java/com/fantion/backend/member/repository/MemberRepository.java
  src/main/java/com/fantion/backend/member/repository/RatingHistoryRepository.java
  src/main/java/com/fantion/backend/member/service/MemberService.java
  src/main/java/com/fantion/backend/member/service/impl/MemberServiceImpl.java
  src/main/java/com/fantion/backend/payment/dto/PaymentDto.java
  src/main/java/com/fantion/backend/payment/service/impl/PaymentServiceImpl.java
  src/main/resources/application.yml
Labels: enhancement, refactorign

#61 Refactor : 낙찰시 발생한 오류 수정
  src/main/java/com/fantion/backend/auction/repository/BidRepository.java
  src/main/java/com/fantion/backend/auction/service/impl/BidServiceImpl.java
  src/main/resources/application.yml
Labels: refactoring

#63 (feat:swagger)
  build.gradle
  src/main/java/com/fantion/backend/common/component/S3Uploader.java
  src/main/java/com/fantion/backend/common/config/SecurityConfiguration.java
  src/main/java/com/fantion/backend/common/config/SwaggerConfig.java
  src/main/java/com/fantion/backend/common/dto/ResultDTO.java
  src/main/java/com/fantion/backend/exception/CustomExceptionHandler.java
  src/main/java/com/fantion/backend/exception/ErrorCode.java
  src/main/java/com/fantion/backend/exception/impl/TossAPIException.java
  src/main/java/com/fantion/backend/member/controller/MemberController.java
  src/main/java/com/fantion/backend/member/dto/CheckDto.java
  src/main/java/com/fantion/backend/member/dto/MemberDto.java
  src/main/java/com/fantion/backend/member/dto/RatingRequestDto.java
  src/main/java/com/fantion/backend/member/dto/ResetPasswordDto.java
  src/main/java/com/fantion/backend/member/dto/SigninDto.java
  src/main/java/com/fantion/backend/member/dto/SignupDto.java
  src/main/java/com/fantion/backend/member/dto/TokenDto.java
  src/main/java/com/fantion/backend/member/service/MemberService.java
  src/main/java/com/fantion/backend/member/service/impl/MemberServiceImpl.java
  src/main/java/com/fantion/backend/payment/component/PaymentClient.java
  src/main/java/com/fantion/backend/payment/controller/PaymentController.java
  src/main/java/com/fantion/backend/payment/dto/PaymentDto.java
  src/main/java/com/fantion/backend/payment/dto/PaymentResponseDto.java
  src/main/java/com/fantion/backend/payment/service/PaymentService.java
  src/main/java/com/fantion/backend/payment/service/impl/PaymentServiceImpl.java
  src/main/resources/application.yml
Labels: enhancement

#64 Dev
  build.gradle
  src/main/java/com/fantion/backend/auction/dto/BuyNowDto.java
  src/main/java/com/fantion/backend/auction/repository/BidRepository.java
  src/main/java/com/fantion/backend/auction/service/impl/BidServiceImpl.java
  src/main/java/com/fantion/backend/common/component/S3Uploader.java
  src/main/java/com/fantion/backend/common/config/SecurityConfiguration.java
  src/main/java/com/fantion/backend/common/config/SwaggerConfig.java
  src/main/java/com/fantion/backend/common/dto/ResultDTO.java
  src/main/java/com/fantion/backend/exception/CustomExceptionHandler.java
  src/main/java/com/fantion/backend/exception/ErrorCode.java
  src/main/java/com/fantion/backend/exception/impl/TossAPIException.java
  src/main/java/com/fantion/backend/member/controller/MemberController.java
  src/main/java/com/fantion/backend/member/dto/CheckDto.java
  src/main/java/com/fantion/backend/member/dto/MemberDto.java
  src/main/java/com/fantion/backend/member/dto/RatingRequestDto.java
  src/main/java/com/fantion/backend/member/dto/ResetPasswordDto.java
  src/main/java/com/fantion/backend/member/dto/SigninDto.java
  src/main/java/com/fantion/backend/member/dto/SignupDto.java
  src/main/java/com/fantion/backend/member/dto/TokenDto.java
  src/main/java/com/fantion/backend/member/service/MemberService.java
  src/main/java/com/fantion/backend/member/service/impl/MemberServiceImpl.java
  src/main/java/com/fantion/backend/payment/component/PaymentClient.java
  src/main/java/com/fantion/backend/payment/controller/PaymentController.java
  src/main/java/com/fantion/backend/payment/dto/PaymentDto.java
  src/main/java/com/fantion/backend/payment/dto/PaymentResponseDto.java
  src/main/java/com/fantion/backend/payment/service/PaymentService.java
  src/main/java/com/fantion/backend/payment/service/impl/PaymentServiceImpl.java
Labels: enhancement, refactoring

#65 (feat:my-balance)
  src/main/java/com/fantion/backend/exception/ErrorCode.java
  src/main/java/com/fantion/backend/member/controller/MemberController.java
  src/main/java/com/fantion/backend/member/dto/MyBalanceDto.java
  src/main/java/com/fantion/backend/member/dto/SignupDto.java
  src/main/java/com/fantion/backend/member/repository/BalanceHistoryRepository.java
  src/main/java/com/fantion/backend/member/service/MemberService.java
  src/main/java/com/fantion/backend/member/service/impl/MemberServiceImpl.java
  src/main/java/com/fantion/backend/payment/service/impl/PaymentServiceImpl.java
Labels: enhancement

#66 Dev
  src/main/java/com/fantion/backend/exception/ErrorCode.java
  src/main/java/com/fantion/backend/member/controller/MemberController.java
  src/main/java/com/fantion/backend/member/dto/MyBalanceDto.java
  src/main/java/com/fantion/backend/member/dto/SignupDto.java
  src/main/java/com/fantion/backend/member/repository/BalanceHistoryRepository.java
  src/main/java/com/fantion/backend/member/service/MemberService.java
  src/main/java/com/fantion/backend/member/service/impl/MemberServiceImpl.java
  src/main/java/com/fantion/backend/payment/service/impl/PaymentServiceImpl.java
Labels: enhancement

#69 (refactor:toss-cancel)
  src/main/java/com/fantion/backend/payment/dto/CancelDto.java
  src/main/java/com/fantion/backend/payment/repository/PaymentRepository.java
  src/main/java/com/fantion/backend/payment/service/impl/PaymentServiceImpl.java
Labels: refactoring

#73 Dev
  src/main/java/com/fantion/backend/FantionApplication.java
  src/main/java/com/fantion/backend/common/config/SwaggerConfig.java
  src/main/java/com/fantion/backend/payment/component/PaymentClient.java
  src/main/java/com/fantion/backend/payment/dto/CancelDto.java
  src/main/java/com/fantion/backend/payment/service/impl/PaymentServiceImpl.java
Labels: refactoring

#81 (refactor:auction-service-swagger)
  src/main/java/com/fantion/backend/auction/controller/AuctionController.java
  src/main/java/com/fantion/backend/auction/dto/AuctionDto.java
  src/main/java/com/fantion/backend/auction/dto/CategoryDto.java
  src/main/java/com/fantion/backend/auction/service/AuctionService.java
  src/main/java/com/fantion/backend/auction/service/impl/AuctionServiceImpl.java
  src/main/java/com/fantion/backend/auction/service/impl/BidServiceImpl.java
  src/main/java/com/fantion/backend/exception/ErrorCode.java
  src/main/java/com/fantion/backend/member/controller/MemberController.java
  src/main/java/com/fantion/backend/member/dto/ProfileImageResponseDto.java
  src/main/java/com/fantion/backend/member/service/MemberService.java
  src/main/java/com/fantion/backend/member/service/impl/MemberServiceImpl.java
  src/main/java/com/fantion/backend/payment/service/impl/PaymentServiceImpl.java
  src/main/java/com/fantion/backend/type/BalanceType.java
  src/main/resources/application.yml
Labels: refactoring

#83 Refactor : 입찰 및 즉시구매 검증, 예치금 생성일자 저장
  src/main/java/com/fantion/backend/auction/controller/BidController.java
  src/main/java/com/fantion/backend/auction/dto/BidAuctionCancelDto.java
  src/main/java/com/fantion/backend/auction/repository/AuctionRepository.java
  src/main/java/com/fantion/backend/auction/service/impl/BidServiceImpl.java
  src/main/java/com/fantion/backend/exception/ErrorCode.java
Labels: refactoring

#85 Dev
  src/main/java/com/fantion/backend/auction/controller/AuctionController.java
  src/main/java/com/fantion/backend/auction/controller/BidController.java
  src/main/java/com/fantion/backend/auction/dto/AuctionDto.java
  src/main/java/com/fantion/backend/auction/dto/BidAuctionCancelDto.java
  src/main/java/com/fantion/backend/auction/dto/CategoryDto.java
  src/main/java/com/fantion/backend/auction/repository/AuctionRepository.java
  src/main/java/com/fantion/backend/auction/service/AuctionService.java
  src/main/java/com/fantion/backend/auction/service/impl/AuctionServiceImpl.java
  src/main/java/com/fantion/backend/auction/service/impl/BidServiceImpl.java
  src/main/java/com/fantion/backend/exception/ErrorCode.java
Labels: refactoring

#87 Refactor/favorite category
  src/main/java/com/fantion/backend/auction/dto/AuctionDto.java
  src/main/java/com/fantion/backend/auction/repository/AuctionRepository.java
  src/main/java/com/fantion/backend/auction/repository/BidRepository.java
  src/main/java/com/fantion/backend/auction/service/impl/AuctionServiceImpl.java
Labels: refactoring
